// 跑马 Marquee
// 流星 Meteor
// 激光 Laser
// 流水 Flowing Water
// 拉幕 Curtain
// 幻彩 Rainbow

import { t } from 'i18next';

// 追光 Chasing
const scrollData = [
  {
    title: t('Marquee'),
    key: 'Marquee',
    icon: require('../../assets/light-glow-modes/Marquee.png'),
  },
  {
    title: t('Meteor'),
    key: 'Meteor',
    icon: require('../../assets/light-glow-modes/Meteor.png'),
  },
  {
    title: t('Laser'),
    key: 'Laser',
    icon: require('../../assets/light-glow-modes/Laser.png'),
  },
  {
    title: t('Flowing Water'),
    key: 'Flowing Water',
    icon: require('../../assets/light-glow-modes/Flowing-Water.png'),
  },
  {
    title: t('Curtain'),
    key: 'Curtain',
    icon: require('../../assets/light-glow-modes/Curtain.png'),
  },
  {
    title: t('Rainbow'),
    key: 'Rainbow',
    icon: require('../../assets/light-glow-modes/Rainbow.png'),
  },
  {
    title: t('Chasing'),
    key: 'Chasing',
    icon: require('../../assets/light-glow-modes/Chasing.png'),
  },
];
const CarouselOneData = [
  {
    title: t('Marquee'),
    key: 'Marquee',
    icon: require('../../assets/light-glow-modes/Marquee.png'),
  },
  {
    title: t('Meteor'),
    key: 'Meteor',
    icon: require('../../assets/light-glow-modes/Meteor.png'),
  },
  {
    title: t('Laser'),
    key: 'Laser',
    icon: require('../../assets/light-glow-modes/Laser.png'),
  },
  {
    title: t('Flowing Water'),
    key: 'Flowing Water',
    icon: require('../../assets/light-glow-modes/Flowing-Water.png'),
  },
  {
    title: t('Curtain'),
    key: 'Curtain',
    icon: require('../../assets/light-glow-modes/Curtain.png'),
  },
];
const CarouselTwoData = [
  {
    title: t('Rainbow'),
    key: 'Rainbow',
    icon: require('../../assets/light-glow-modes/Rainbow.png'),
  },
  {
    title: t('Chasing'),
    key: 'Chasing',
    icon: require('../../assets/light-glow-modes/Chasing.png'),
  },
  {
    title: t('Marquee'),
    key: 'Marquee',
    icon: require('../../assets/light-glow-modes/Marquee.png'),
  },
  {
    title: t('Meteor'),
    key: 'Meteor',
    icon: require('../../assets/light-glow-modes/Meteor.png'),
  },
  {
    title: t('Laser'),
    key: 'Laser',
    icon: require('../../assets/light-glow-modes/Laser.png'),
  },
];
const CarouselThreeData = [
  {
    title: t('Flowing Water'),
    key: 'Flowing Water',
    icon: require('../../assets/light-glow-modes/Flowing-Water.png'),
  },
  {
    title: t('Curtain'),
    key: 'Curtain',
    icon: require('../../assets/light-glow-modes/Curtain.png'),
  },
  {
    title: t('Rainbow'),
    key: 'Rainbow',
    icon: require('../../assets/light-glow-modes/Rainbow.png'),
  },
  {
    title: t('Chasing'),
    key: 'Chasing',
    icon: require('../../assets/light-glow-modes/Chasing.png'),
  },
  {
    title: t('Marquee'),
    key: 'Marquee',
    icon: require('../../assets/light-glow-modes/Marquee.png'),
  },
];
const glowModes = {
  Rainbow: [
    'Auto-cycle',
    'Iris Rainbow',
    'Color Gradient',
    'Red-Yellow Gradient',
    'Red-Purple Gradient',
    'Green-Cyan Gradient',
    'Green-Yellow Gradient',
    'Blue-Purple Gradient',
  ],
  Marquee: [
    'Red Horse Race',
    'Green Horse Race',
    'Blue Horse Race',
    'Yellow Horse Race',
    'Cyan Horse Race',
    'Purple Horse Race',
    'White Horse Race',
    'Red Movement',
    'Green Movement',
    'Blue Movement',
    'Yellow Movement',
    'Cyan Movement',
    'Purple Movement',
    'White Movement',
    'Color Movement',
    'Blue-Green-Red',
    'Purple-Cyan-Yellow',
    'Blue-Purple-Cyan-Yellow',
    'Blue-Green-Cyan-Yellow',
    'White bkgrd with Red Dots',
    'Red bkgrd with Green Dots',
    'Green bkgrd with Blue Dots',
    'Blue bkgrd with Yellow Dots',
    'Yellow bkgrd with Cyan Dots',
    'Cyan bkgrd with Purple Dots',
    'Purple bkgrd with White Dots',
    'Red bkgrd with White Dots',
    'Blue bkgrd with Green Dots',
    'Blue bkgrd with Red Dots',
    'Purple bkgrd with Yellow Dots',
    'Yellow bkgrd with White Dots',
    'White bkgrd with Yellow Dots',
    'Red bkgrd with Rainbow',
    'Green bkgrd with Rainbow',
    'Blue bkgrd with Rainbow',
    'Yellow bkgrd with Rainbow',
    'Cyan bkgrd with Rainbow',
    'Purple bkgrd with Rainbow',
    'White bkgrd with Rainbow',
  ],
  Laser: [
    'Color Energy',
    'Color Jump',
    'Red-Green-Blue Jump',
    'Yellow-Cyan-Purple Jump',
    'Color Strobe',
    'Red-Green-Blue Strobe',
    'Yellow-Cyan-Purple Strobe',
  ],
  'Flowing Water': [
    'Color Fade',
    'Yellow-Green-Red Fade',
    'Purple-Cyan-Yellow Fade',
    'Six-Color Fade with Red',
    'Six-Color Fade with Green',
    'Six-Color Fade with Blue',
    'Six-Color Fade with Cyan',
    'Six-Color Fade with Yellow',
    'Six-Color Fade with Purple',
    'Six-Color Fade with White',
    'Color Flow',
    'Green-Blue-Red Flow',
    'Yellow-Cyan-Purple Flow',
    'Red-Green Flow',
    'Green-Blue Flow',
    'Yellow-Blue Flow',
    'Yellow-Cyan Flow',
    'Purple-Cyan Flow',
    'Black-White Flow',
  ],
  Meteor: [
    'Color Trailing',
    'Red Trailing',
    'Green Trailing',
    'Blue Trailing',
    'Yellow Trailing',
    'Cyan Trailing',
    'Purple Trailing',
    'White Trailing',
  ],
  Chasing: [
    'Color Chasing',
    'Red-Green-Blue Chasing',
    'Yellow-Cyan-Purple Chasing',
    'Color Floating',
    'Red-Green-Blue Floating',
    'Yellow-Cyan-Purple Floating',
    'White-Red-White Flow',
    'White-Green-White Flow',
    'White-Blue-White Flow',
    'White-Yellow-White Flow',
    'White-Cyan-White Flow',
    'White-Purple-White Flow',
    'Red-White-Red Flow',
    'Green-White-Green Flow',
    'Blue-White-Blue Flow',
    'Yellow-White-Yellow Flow',
    'Cyan-White-Cyan Flow',
    'Purple-White-Purple Flow',
  ],
  'Theater Curtain': [
    'Color Curtain',
    'Red-Green-Blue Curtain',
    'Yellow-Cyan-Purple Curtain',
    'Red Curtain',
    'Green Curtain',
    'Blue Curtain',
    'Yellow Curtain',
    'Cyan Curtain',
    'Purple Curtain',
    'White Curtain',
    'Color Wash',
    'Red-Green-Blue Wash',
    'Yellow-Cyan-Purple Wash',
  ],
};
export {
  scrollData,
  CarouselOneData,
  CarouselTwoData,
  CarouselThreeData,
  glowModes,
};
